### ISSUE TITLE
Doesn't show Step names in the report

### ISSUE THREAD

**Issue by ognezdyonova** [allure-framework/allure-codeception#10]
I have simple Codeception Acceptance testcase (I'll include code letter).
I ran the test and generate report via command:

C:\Users\ognezdyonova\workspace\InvoiceCentralCodeception>allure generate -v 1.4.1 C:\Users\ognezdyonova\workspace\InvoiceCentralCodeception\allure-results

But in the report itself I can't see the Step names or method names only text "Step" which makes this report useless.

I attached screenshot. 

Code of testcase:

<?php

/*******************************************
- Created by O. Gnezdyonova              *
- Created on 4/7/2015                    *
- BA-125                                 *
  ******************************************/

use IC\Objects\PlaidACHPage;
use IC\Objects\OpenTabPage;

/**
- @var AcceptanceTester
  */

$I = new AcceptanceTester($scenario);

$I->wantTo('Test ACH Payments');

$I->icACHDbUpdate($I, ACHPaymentData::$icUname);

/**
- Login to IC with Helper Class
- Validating the Open Invoice page
  */

$I->icLogin($I, ACHPaymentData::$icUname, ACHPaymentData::$icPwd);

/**
- Test Scenario 1: Add bank account via plaid throw payment process.
  */
  $I->wantTo('Test Scenario 1: Add bank account via plaid throw payment process.');

$I->checkOption(['xpath' => '//input[@value="'.ACHPaymentData::$selectInvoice1.'"]']);
$I->click(['xpath' => OpenTabPage::$ic_paySelectedBtn]);
$I->waitForText('Number of Invoices:');
$I->selectOption('form select[name=payment_paymentAccount_'.ACHPaymentData::$selectInvoice1.']', ACHPaymentData::$achAddNewAccount);
$I->waitForText('Option One: Select your bank', 2);

//Select Bank from the list
$I->icSelectBank($I, PlaidACHPage::$ic_bankOfAmerica);
$I->waitForText('Log in', 2);

//Login to the bank account
$I->icLoginBank($I, PlaidACHPage::$ic_plaidUser, PlaidACHPage::$ic_plaidPwd);
$I->waitForText('Verify Account');

//Verify MFA question
$I->icMfaQuestion($I, PlaidACHPage::$ic_plaidResponse);
$I->waitForText('Choose Accounts', 2);

//Select Primary Checking Account
$I->icSelectPrimaryChecking($I, PlaidACHPage::$ic_regularChecking1, PlaidACHPage::$ic_regularChecking1);

$I->fillField(['xpath' => '//input[@id="payment_paymentAmount_'.ACHPaymentData::$selectInvoice1.'"]'],ACHPaymentData::$selectAchAmount1);
$I->icAddMemoQuick($I, CCPaymentData::$row, ACHPaymentData::$memo);
$I->click('Next');

// Verify the correct payment amount is showing as Total Amount in Authorization and Confirmation page
$I->icVerifyTotalAmount($I, ACHPaymentData::$selectAchAmount1);

$I->wait(2);
$I->click('close');

// Verify that we are navigating back to the Home page after successful payment and then Cancel the payment
$I->icCancelPayment($I);

// Delete CC payment account
$I->icDeleteACHPayAccount($I, ACHPaymentData::$icUname);

![2015_04_22_16_10_46_allure_dashboard](https://cloud.githubusercontent.com/assets/7072308/7284254/608b0e04-e90a-11e4-8018-cf5886b6bf47.jpg)

**Comment by vania-pooh** [comment]
Could you please check what is returned in this line: https://github.com/allure-framework/allure-codeception/blob/master/src/Yandex/Allure/Adapter/AllureAdapter.php#L212 ?

**Comment by Mitrichius** [comment]
#15
