### ISSUE TITLE
Update for Codeception 2.2

### ISSUE THREAD

**Issue by s-radyuk** [allure-framework/allure-codeception#18]
Could you please provide an update for compatibility with Codeception 2.2 ?

**Comment by vania-pooh** [comment]
Any pull requests are welcome. No free time for the moment. :'(

**Comment by Sereda-Fazen** [comment]
Tell me please in future you plan to update for Codeception 2.2?

**Comment by vania-pooh** [comment]
As I said it would be great if somebody sends me a PR.
