### ISSUE TITLE
How to config custom ignored annotations?

### ISSUE THREAD

**Issue by jilu1** [allure-framework/allure-codeception#26]
Hello!
I tried to add custom ignored annotations with something like
```xml
    config:
          Yandex\Allure\Adapter\AllureAdapter:
              deletePreviousResults: true
              outputDirectory: allure-results
              ignoredAnnotations:
                  - myAnnotation1
                  - myAnnotation2
```
I can see that they are applied to config value, but these config values are not used in the AllureAdapter class. Is it the correct way to configure custom ignored annotations or is it a bug? Thanks!

**Comment by jilu1** [comment]
Thank you for your quick response!

**Comment by vania-pooh** [comment]
Let's then close this.
