### ISSUE TITLE
Invalid start/stop time format

### ISSUE THREAD

**Issue by baev** [allure-framework/allure-codeception#36]
#### from https://github.com/allure-framework/allure2/issues/609

I have an issue while trying to generate a report.

#### Steps to reproduce

1. I am generating the .xml file from Codeception using [allure-codeception](https://github.com/allure-framework/allure-codeception).
2. I am running the allure generate command to produce the report

#### What I see
An exception:
```
Exception in thread "main" java.lang.NumberFormatException: For input string: 
"1.50642981892E+12"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
```

The XML file line that includes this string is:

```xml
<alr:test-suite xmlns:alr="urn:model.allure.qatools.yandex.ru" start="1.50642981892E+12" stop="1.5064299142E+12" version="1.4.0">
```

#### What I expect to see

The message that the report is created.

#### Environment

| Allure version | 2.3.5 |
| --- | --- |
| Test framework | Codeception@2.3.5 |
| Allure adaptor | allure-codeception@1.2.4 |
| Generate report using | allure-command-line-tool@2.3.5 |

**Comment by kouratoras** [comment]
@baev any news on this issue?

**Comment by baev** [comment]
@kouratoras our team has no PHP dev at the moment, so could you please send a PR with fixes? The problem is that E notation is not supported and also +12 seems to be nano time but it should be unix time in milliseconds

**Comment by kouratoras** [comment]
@baev ok, I will take a look and get back to you soon.

Do you have an example of a working pair of start/end times?

**Comment by baev** [comment]
https://github.com/allure-framework/allure2/blob/master/allure-generator/test-data/demo/d3df6bc4-475d-436b-b99f-3a4eaba6d1a8-testsuite.xml

> and also +12 seems to be nano time but it should be unix time in milliseconds

+12 is mills, ma fault

**Comment by kouratoras** [comment]
This is an issue only in MacOS, as date is different than GNU's coreutils date (which can be installed using brew). Let's close it.
