### ISSUE TITLE
Codeception 4 support

### ISSUE THREAD

**Issue by luckyraul** [allure-framework/allure-codeception#50]
https://codeception.com/12-18-2019/codeception-4.html

**Comment by monotonesol** [comment]
Tried to fork and play with it, looks like it works, just needed to update composer.json maybe @DavertMik knows more

**Comment by dasmelch** [comment]
Are there any news about this update? Version 4 of codeception got some nice benefits for us and we don't want to loose the allure plugin. ;)

**Comment by monotonesol** [comment]
No Updates. I will try to contact @DavertMik personally, might be it will help
