### ISSUE TITLE
Tests statistics in the report is not complete since 1.4.1

### ISSUE THREAD

**Issue by amratya01** [allure-framework/allure-codeception#54]
the number of tests decreased tragically on the report generated. Normally I have around 500 tests executed, since the latest release I can only see 154 tests.

What I checked:
- the execution time still the same.
- the output folder for the xml files, it has all the info about all tests
- the testsuite.xml files inside Allure results folder, it has records for all the tests

so, everything was fine except the report itself, so I guess the problem would be on the report generation process itself.

The number of tests went back to normal when I downgraded to 1.4.0

**Comment by amratya01** [comment]
Some more details, I discovered that with the new release it is not considering the execution parameters for the test as individuals, but as retries. I use codeception to run the tests, the command is parameterised for different countries shop, running on different platforms (chrome, android) for every country. 

So it is quite often that the same test is executed 4-6 times with different steps according to the predefined configs and the parameter mentioned on the execution command.

the command: 
`vendor/bin/codecept run --steps tests/path/testnameCest --env=quality, country, platform`
platform: Chromeheadless, Androidheadless

On the old release, these different runs were recognised as standalone tests, while after updating to the last (current) release, these runs are considered retries.

**Comment by amratya01** [comment]
#56

**Comment by baev** [comment]
cloud be fixed in 2.0.0 release. If not, feel free to reopen the issue
