### ISSUE TITLE
Annotations autoload?

### ISSUE THREAD

**Issue by barsukov2** [allure-framework/allure-codeception#64]
Hi!
We are using allure-framework/allure-codeception
And we see that in every Cest you need to use Annotations classes, like
```
use Yandex\Allure\Adapter\Annotation\Title;
use Yandex\Allure\Adapter\Annotation\Description;
... etc
```
May be we can somehow 'globally' use/autoload this classes and do not write them every time?
Appreciate any ideas, thanks

**Comment by eduard-sukharev** [comment]
You could probably do it the following way:
```php
<?php

use Yandex\Allure\Adapter\Annotation as Allure;
```
and then annotate the following way:
```
/**
 * @Allure/Title("Test title here")
 **/
```
Modify the improt to your taste.

**Comment by barsukov2** [comment]
> @Allure/Title("Test title here")

Thanks for tip!
But unfortunately it don't work :c

**Comment by amratya01** [comment]
@barsukov2 use it like this

`@Allure\Title("Test title here")`

**Comment by barsukov2** [comment]
> @barsukov2 use it like this
> 
> ```
> /**
>  * @Allure\Title("Test title here")
>  **/
> ```

That's works, thanks!
And also i will share that i add Doctrine Annotations plugin to my IDE, and it simplifies job :)
