### ISSUE TITLE
php 8 support

### ISSUE THREAD

**Issue by barsukov2** [allure-framework/allure-codeception#67]
Hey guys,
we're planning to go on php8.
So, ```composer why-not php 8``` tells me 
```jms/serializer             1.14.1  requires  php (^5.5|^7.0)```

That's because
allure-framework/allure-codeception  require "allure-framework/allure-php-api": "~1.2.1"
and allure-framework/allure-php-api require "jms/serializer": "^0.16 || ^1.0"

Do we have any plans to make support of newer versions allure-framework/allure-php-api (that supports jms/serializer upper versions)?

**Comment by ihor-sviziev** [comment]
Hi @barsukov2,
FYI there is version [1.5.0](https://github.com/allure-framework/allure-codeception/releases/tag/1.5.0) available, that has a new dependency
https://github.com/allure-framework/allure-codeception/blob/af67f9834f6631574dae025c97562c42dc6773aa/composer.json#L22

So the issue looks fixed

**Comment by barsukov2** [comment]
@ihor-sviziev You're right!
Guys, thank you! :)
